from __future__ import annotations
import os
import re
import shlex
from pathlib import Path

from .util import log
from .util.run import run_sudo, run
from .topology import _mask


def _parse_cpu_range(spec: str) -> set[int]:
    """"0-3,8-15" -> {0,1,2,3,8,9,...,15}. Inverse of topology._mask()."""
    cpus: set[int] = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            lo, hi = part.split("-", 1)
            cpus.update(range(int(lo), int(hi) + 1))
        else:
            cpus.add(int(part))
    return cpus

DROPIN_PATH = Path("/etc/default/grub.d/90-hyphaed.cfg")
GRUB_DEFAULT = Path("/etc/default/grub")
GRUB_DEFAULT_DIR = Path("/etc/default/grub.d")
# Custom GRUB script that overrides menu-entry text for hyphaed kernels.
GRUB_LABEL_SCRIPT = Path("/etc/grub.d/09_hyphaed_label")
GRUB_LABEL_SCRIPT_BODY = '''#!/bin/sh
# Auto-generated by hyphaed. Tweaks the GRUB menu so hyphaed-built
# kernels show a friendly suffix instead of the bare version string.
exec tail -n +3 "$0"
# This file provides a hook only — the real entries are generated by
# 10_linux (Ubuntu's loader). We *amend* them via /etc/grub.d/40_custom
# style sed in the output, but the cleanest approach is GRUB_DISTRIBUTOR.
# See /etc/default/grub.d/91-hyphaed-label.cfg for the actual override.
'''
GRUB_LABEL_DROPIN = Path("/etc/default/grub.d/91-hyphaed-label.cfg")
GRUB_LABEL_DROPIN_BODY = '''# Friendly label for hyphaed-built kernels in the GRUB menu.
# Affects how 10_linux generates menu entries on this machine.
GRUB_DISTRIBUTOR_HYPHAED="Ubuntu (hyphaed: gaming · AI · VM tuned)"
# Bump timeout so the user has time to choose between -generic and -hyphaed.
if [ -z "${GRUB_TIMEOUT}" ] || [ "${GRUB_TIMEOUT}" = "0" ]; then
    GRUB_TIMEOUT=5
    GRUB_TIMEOUT_STYLE=menu
fi
'''


CMDLINE_COMMON = [
    "iommu=pt",
    "transparent_hugepage=madvise",
    "mitigations=auto",
    # Belt-and-braces for the RT_GROUP_SCHED regression fixed in fragment
    # 12-scheduler-bore-scx.config: with CONFIG_RT_GROUP_SCHED=y on a
    # cgroup-v2-unified system, rt_runtime is 0 for every non-root task group and
    # rtkit/PipeWire cannot obtain SCHED_RR. Harmless no-op on kernels built with
    # the symbol unset; keeps RT usable if an older hyphaed kernel is booted.
    "rt_group_sched=0",
]

CMDLINE_INTEL = [
    "intel_iommu=on,igfx_off",
    "intel_pstate=active",
    "split_lock_detect=warn",
]

CMDLINE_AMD = [
    "amd_iommu=on",
    "amd_pstate=active",
]

# Keys that hyphaed always composes into the drop-in even if GreenBoost (or
# another tool) has already set a conflicting value in /etc/default/grub.
# The drop-in appends, so last-wins on the kernel cmdline neutralises the
# existing value for hyphaed boots without touching the main grub file.
POLICY_KEYS: frozenset[str] = frozenset({"mitigations"})

CMDLINE_NVIDIA_WAYLAND = [
    "nvidia-drm.modeset=1",
    "nvidia.NVreg_PreserveVideoMemoryAllocations=1",
    "nvidia.NVreg_EnableGpuFirmware=1",
]

# Boot-only PCIe link power tuning — lowest latency for CUDA H2D/D2H and
# GreenBoost DDR/NVMe<->VRAM tiering. A runtime daemon can't change ASPM
# policy reliably, so this belongs on the cmdline, not in GreenBoost.
#
# 2026-08-18: this said `pcie_aspm=off` for its entire history, and that did
# NOT do what the comment above claims. The two values are not synonyms:
#
#   pcie_aspm=off          kernel does not touch ASPM at all. Whatever the
#                          BIOS programmed stays programmed.
#   pcie_aspm=performance  kernel actively DISABLES ASPM on every link.
#
# Verified live on this box while running with `pcie_aspm=off` on the
# cmdline: /sys/module/pcie_aspm/parameters/policy reads `[default]`, not
# `performance`, and the RTX 5070's own link reports `LnkCtl: ASPM L1
# Enabled`. So the setting intended to give the GPU link the lowest possible
# latency had left BIOS-enabled L1 in place for five kernel builds. The repo's
# The project notes called this combination "confirmed optimal"; it was never
# confirmed, it was assumed from the option's name.
#
# This matters here more than on a general-purpose desktop: decode on this
# box is ~94% PCIe transfer time, and L1 entry/exit sits on exactly that path
# (the GPU's own LnkCap advertises "Exit Latency L1 unlimited").
#
# Chassis-gated. Disabling ASPM everywhere costs idle power on every link,
# which is free on a mains-powered desktop and is not free on machine 2, the
# Ryzen AI 9 laptop. Laptops keep the firmware default.
CMDLINE_GPU_PERF_DESKTOP = [
    "pcie_aspm=performance",
]
CMDLINE_GPU_PERF_LAPTOP = [
    "pcie_aspm=off",
]

# Back-compat alias: some callers/tests referenced this name directly.
CMDLINE_GPU_PERF = CMDLINE_GPU_PERF_DESKTOP

# ── Opt-in PCIe byte-reduction levers (spark-parity-survey.md Track 1.3/1.5) ──
# Neither of these is composed by default — both are exposed only via the
# enable_pcie_bus_perf / enable_pcie_acs_override kwargs on compose_cmdline()
# below, defaulting to False. A caller (future CLI flag, or a preset field
# a user deliberately sets) has to opt in explicitly. This is deliberate,
# not an oversight: both carry a real tradeoff that only the operator can
# judge for their own topology/threat model — see each constant's comment.

# `pci=pcie_bus_perf` makes the kernel set every device's MaxPayloadSize to
# the largest value the whole PCIe tree agrees on (and MaxReadReq to match),
# instead of leaving firmware's (often conservative) negotiated value in
# place. Confirmed via diagnostics/pcie-mps-mrrs-check.sh that this box's
# /proc/cmdline carries no `pci=` option at all today, so MPS sits at
# whatever firmware set. Real, if modest (~3-11%), TLP-header-overhead
# reduction on every PCIe transaction — see spark-parity-survey.md Track 1.3.
# RISK: if any bridge in the topology advertises a smaller MaxPayload than
# its neighbors, `pcie_bus_perf` can push a device into a configuration a
# buggy bridge mishandles. Run diagnostics/pcie-mps-mrrs-check.sh FIRST to
# confirm every hop agrees before ever setting enable_pcie_bus_perf=True.
CMDLINE_PCIE_BUS_PERF = [
    "pci=pcie_bus_perf",
]

# `pcie_acs_override=` disables ACS (Access Control Services) enforcement on
# the root port, letting NVMe<->GPU P2P DMA (GPUDirect Storage) go directly
# peer-to-peer instead of being forced up through the root complex and back
# down. patches/custom/0018-tkg-pci-acs-override.patch (already forward-
# ported, dormant in the series) is what makes this boot option available at
# all — this constant is the cmdline half of actually using it.
# RISK, stated explicitly, not hidden in a comment nobody reads: disabling
# ACS weakens IOMMU isolation BETWEEN PCIe devices/functions. On a box that
# also runs VMware VMs (this one does — has_vmware=True in every recorded
# hardware profile), that is a real security tradeoff, not a formality —
# it means one passthrough-adjacent device could potentially snoop or
# interfere with DMA traffic belonging to another. Single-user workstation,
# operator's call; never composed automatically.
CMDLINE_PCIE_ACS_OVERRIDE = [
    "pcie_acs_override=downstream,multifunction",
]


def compose_cmdline(
    profile,
    preset_extra: list[str] | None = None,
    *,
    skip_keys_present_in: list[str] | None = None,
    enable_pcie_bus_perf: bool = False,
    enable_pcie_acs_override: bool = False,
) -> list[str]:
    """Compose the drop-in cmdline append.

    skip_keys_present_in: an existing token list (e.g. from
    `read_current_cmdline_config()`). Any key already set there is
    dropped from our output to avoid double-up with greenboost or
    user-managed entries.

    enable_pcie_bus_perf / enable_pcie_acs_override: opt-in PCIe
    byte-reduction levers, both default False (see CMDLINE_PCIE_BUS_PERF /
    CMDLINE_PCIE_ACS_OVERRIDE above for what each does and why neither is
    on by default). No existing caller sets either, so this is additive —
    every current call site's behavior is unchanged.
    """
    vendor_parts: list[str] = []
    if profile.cpu_vendor == "intel":
        vendor_parts = list(CMDLINE_INTEL)
    elif profile.cpu_vendor == "amd":
        vendor_parts = list(CMDLINE_AMD)
    parts: list[str] = list(CMDLINE_COMMON) + vendor_parts
    if profile.p_thread_mask:
        # Default IRQ affinity for anything that doesn't request its own
        # (confirmed on this box: the GPU's MSI-X completion vectors land
        # on E-core threads with no irqbalance running — directly opposite
        # of 13-energy-hybrid.config's intent to keep E-cores off the
        # latency-critical path). Biases the GPU's per-token completion
        # interrupt, NVMe, NIC, etc. onto P-cores by default.
        irq_cpus = _parse_cpu_range(profile.p_thread_mask)
        # Exclude GreenBoost's "golden" nohz_full core range if it's
        # published (cross-check, best-effort — see hyphaed/greenboost.py).
        # Found live 2026-07-24: without this, the full P-thread mask
        # (0-15) overlaps nohz_full=4-7, so a cluster/RPC/NCCL NIC
        # interrupt landing on a golden core (IRQ 167/enp4s0 confirmed at
        # smp_affinity_list 0-15, no narrower override) forces a scheduler
        # tick on a core meant to stay tickless mid-inference — silently
        # undermining the isolation nohz_full exists to provide, for
        # exactly the cluster-fabric traffic this workstation now depends
        # on (gb-synapse's --rpc/PP feeder link). irqaffinity is hyphaed's
        # own key (unlike nohz_full/rcu_nocbs, which greenboost writes) so
        # this is the right side to fix it from.
        try:
            from . import greenboost as gb_mod
            gb = gb_mod.find_active_profile()
            if gb is not None:
                golden_min = gb.get_int("golden_cpu_min", -1)
                golden_max = gb.get_int("golden_cpu_max", -1)
                if golden_min >= 0 and golden_max >= golden_min:
                    narrowed = irq_cpus - set(range(golden_min, golden_max + 1))
                    if narrowed:  # never compose an empty mask
                        irq_cpus = narrowed
        except Exception as e:
            log.warn(f"greenboost golden-core cross-check failed (non-fatal): {e}")
        parts.append(f"irqaffinity={_mask(sorted(irq_cpus))}")
    if profile.gpu_vendor == "nvidia":
        parts.extend(CMDLINE_NVIDIA_WAYLAND)
        # See CMDLINE_GPU_PERF_DESKTOP: `off` leaves the BIOS's ASPM config
        # alone, `performance` actually disables it. Desktops want the latter.
        if getattr(profile, "chassis", "unknown") == "laptop":
            parts.extend(CMDLINE_GPU_PERF_LAPTOP)
        else:
            parts.extend(CMDLINE_GPU_PERF_DESKTOP)
    if enable_pcie_bus_perf:
        log.warn(
            "enabling pci=pcie_bus_perf — verify every bridge in the PCIe "
            "topology agrees on MaxPayload first (diagnostics/pcie-mps-mrrs-check.sh)"
        )
        parts.extend(CMDLINE_PCIE_BUS_PERF)
    if enable_pcie_acs_override:
        log.warn(
            "enabling pcie_acs_override= — this weakens IOMMU isolation "
            "between PCIe devices; only enable if you understand the tradeoff "
            "(see CMDLINE_PCIE_ACS_OVERRIDE's comment in hyphaed/grub.py)"
        )
        parts.extend(CMDLINE_PCIE_ACS_OVERRIDE)
    if preset_extra:
        parts.extend(preset_extra)

    if skip_keys_present_in:
        existing_keys = {tok.split("=", 1)[0] for tok in skip_keys_present_in}
        before = len(parts)
        # Policy keys are always composed even if already set elsewhere — the
        # drop-in append wins on the kernel cmdline (last-wins), which is the
        # mechanism that overrides GreenBoost's mitigations=off for hyphaed boots.
        parts = [p for p in parts if p.split("=", 1)[0] not in existing_keys
                 or p.split("=", 1)[0] in POLICY_KEYS]
        skipped = before - len(parts)
        if skipped:
            log.info(f"skipped {skipped} cmdline param(s) already configured elsewhere (likely greenboost)")

    # Hard rule: refuse mitigations=off
    dropped_mitigations = [p for p in parts if p == "mitigations=off"]
    if dropped_mitigations:
        log.warn("dropping mitigations=off from cmdline (policy: all mitigations stay ON)")
    parts = [p for p in parts if p != "mitigations=off"]

    # Dedupe by key: LAST occurrence wins. parts is built in priority order
    # (CMDLINE_BASE, then GPU-specific defaults, then preset_extra last), so
    # a preset's cmdline_extra is meant to override CMDLINE_BASE defaults —
    # e.g. ai-only.yaml overrides the base `transparent_hugepage=madvise`
    # with `=always`. Matches the documented semantics of
    # read_current_cmdline_config() ("last assignment wins"), and matches
    # what GRUB/the kernel cmdline actually does at boot.
    last_idx: dict[str, int] = {}
    for i, p in enumerate(parts):
        key = p.split("=", 1)[0]
        if key in last_idx and parts[last_idx[key]] != p:
            log.warn(
                f"cmdline key '{key}' set twice; override wins "
                f"({p!r}), dropping {parts[last_idx[key]]!r}"
            )
        last_idx[key] = i
    return [parts[i] for i in sorted(last_idx.values())]


def render_dropin(cmdline_parts: list[str]) -> str:
    extra = " ".join(cmdline_parts)
    return (
        "# Auto-generated by hyphaed kernel wizard. Do not edit by hand.\n"
        "# Appended to GRUB_CMDLINE_LINUX_DEFAULT by /etc/grub.d/00_header.\n"
        f'GRUB_CMDLINE_LINUX_DEFAULT="${{GRUB_CMDLINE_LINUX_DEFAULT}} {extra}"\n'
    )


_CMDLINE_RE = re.compile(r'^\s*GRUB_CMDLINE_LINUX_DEFAULT\s*=\s*"(.*)"', re.MULTILINE)


_VAR_REF_RE = re.compile(r"\$\{GRUB_CMDLINE_LINUX_DEFAULT\}|\$GRUB_CMDLINE_LINUX_DEFAULT")


def read_current_cmdline_config() -> list[str]:
    """Return the effective GRUB_CMDLINE_LINUX_DEFAULT tokens as configured
    (NOT what's running). Reads /etc/default/grub then layers /etc/default/grub.d/*.

    Tokens are deduplicated by key: the *last* assignment wins for each key
    (matches kernel cmdline semantics and what GRUB effectively passes).
    """
    raw = ""
    if GRUB_DEFAULT.exists():
        m = _CMDLINE_RE.search(GRUB_DEFAULT.read_text())
        if m:
            raw = m.group(1)
    # apply drop-ins in lexical order (matches update-grub behaviour)
    if GRUB_DEFAULT_DIR.is_dir():
        for f in sorted(GRUB_DEFAULT_DIR.glob("*.cfg")):
            if f.resolve() == DROPIN_PATH.resolve():
                continue
            try:
                m = _CMDLINE_RE.search(f.read_text())
            except OSError:
                continue
            if not m:
                continue
            raw = _VAR_REF_RE.sub(raw, m.group(1))

    tokens = shlex.split(raw)
    # Deduplicate by key, keeping last occurrence (matches kernel cmdline semantics)
    seen: dict[str, int] = {}
    for i, tok in enumerate(tokens):
        key = tok.split("=", 1)[0]
        seen[key] = i
    return [tokens[i] for i in sorted(seen.values())]


def diff_cmdline(current: list[str], proposed_full: list[str]) -> tuple[list[str], list[str], list[str]]:
    """Return (added, removed, kept_same_key_diff_value). Keyed by left-of-=."""
    def keymap(tokens: list[str]) -> dict[str, str]:
        out: dict[str, str] = {}
        for t in tokens:
            k, _, _v = t.partition("=")
            out[k] = t
        return out

    cur = keymap(current)
    new = keymap(proposed_full)
    added = [new[k] for k in new if k not in cur]
    removed = [cur[k] for k in cur if k not in new]
    changed = [f"{cur[k]} → {new[k]}" for k in new if k in cur and cur[k] != new[k]]
    return added, removed, changed


def print_cmdline_diff(current: list[str], proposed_extra: list[str]) -> None:
    """Show a colored diff between current effective cmdline and what we'd
    end up with after the drop-in is applied.
    """
    # The drop-in *appends*, so the new effective is current + proposed_extra,
    # then deduped by key (later wins). But our compose_cmdline already dedupes
    # within proposed_extra; collisions with current are decided by drop-in append.
    after = list(current) + list(proposed_extra)
    seen: dict[str, str] = {}
    for tok in after:
        k, _, _v = tok.partition("=")
        seen[k] = tok
    final = list(seen.values())

    added, removed, changed = diff_cmdline(current, final)
    if not (added or removed or changed):
        log.info("cmdline unchanged")
        return
    if added:
        log.console.print("[ok]+ added[/ok]")
        for x in added:
            log.console.print(f"    + {x}")
    if changed:
        log.console.print("[warn]~ changed[/warn]")
        for x in changed:
            log.console.print(f"    ~ {x}")
    if removed:
        log.console.print("[muted]- removed[/muted]")
        for x in removed:
            log.console.print(f"    - {x}")


def write_dropin(cmdline_parts: list[str], *, dry_run: bool = False) -> tuple[Path, bool]:
    """Write the drop-in idempotently. Returns (path, changed)."""
    content = render_dropin(cmdline_parts)
    if DROPIN_PATH.exists():
        try:
            if DROPIN_PATH.read_text() == content:
                log.info(f"{DROPIN_PATH} already up to date — skipping write")
                return DROPIN_PATH, False
        except OSError:
            pass

    if dry_run:
        log.info(f"would write {DROPIN_PATH}:")
        for line in content.splitlines():
            log.console.print(f"    {line}")
        return DROPIN_PATH, True

    run_sudo(["mkdir", "-p", str(DROPIN_PATH.parent)])
    run_sudo(["tee", str(DROPIN_PATH)], input_str=content, capture=True)
    log.ok(f"wrote GRUB drop-in {DROPIN_PATH}")
    return DROPIN_PATH, True


def update_grub(*, dry_run: bool = False) -> None:
    if dry_run:
        log.info("would run: sudo update-grub")
        return
    run_sudo(["update-grub"])
    log.ok("update-grub completed")


# Confirmed live 2026-07-30 via `cat /boot/grub/grubenv` (world-readable,
# unlike grub.cfg which is root-only 0600 and wasn't accessible to derive an
# --id-string fixture from): saved_entry on this box reads
# "Advanced options for Ubuntu>Ubuntu, with Linux 7.1.1-hyphaed" — GRUB's
# title-path addressing (submenu title > menuentry title), not an --id
# string. This is Canonical's 10_linux script's fixed template
# ("<distributor>, with Linux <uname-r>" nested under "Advanced options for
# <distributor>"). Using the same title-path format here is grounded in what
# this exact system already produces, rather than a guess at --id syntax.
#
# Note GRUB_DISTRIBUTOR_HYPHAED (write_label_dropin() above) is NOT what
# ends up in the title — 10_linux only reads plain GRUB_DISTRIBUTOR, and the
# live grubenv confirms the title is still plain "Ubuntu", not the "hyphaed:
# gaming · AI · VM tuned" custom label. Hardcoded to "Ubuntu" to match; this
# whole module is already Ubuntu-specific (see GRUB_DEFAULT/DROPIN_PATH).
GRUB_MENU_DISTRIBUTOR = "Ubuntu"


def pin_default_kernel(kver: str, *, dry_run: bool = False) -> None:
    """Persistently pin `kver` (e.g. '7.1.5-hyphaed') as the GRUB default
    boot entry via `grub-set-default`, so a future `update-grub` menu
    regeneration can't silently change which kernel boots by default.

    Unlike `grub-reboot` (one-shot), `grub-set-default` writes grubenv's
    saved_entry persistently — the correct semantics here, since the whole
    point is "this stays the intended default until the next hyphaed
    install changes it again".
    """
    entry = f"Advanced options for {GRUB_MENU_DISTRIBUTOR}>{GRUB_MENU_DISTRIBUTOR}, with Linux {kver}"
    if dry_run:
        log.info(f"would run: sudo grub-set-default {entry!r}")
        return
    run_sudo(["grub-set-default", entry])
    log.ok(f"pinned GRUB default boot entry → {kver}")


def write_label_dropin(*, dry_run: bool = False) -> bool:
    """Set GRUB_DISTRIBUTOR + bump GRUB_TIMEOUT to 5s. Returns True if changed."""
    if GRUB_LABEL_DROPIN.exists():
        try:
            if GRUB_LABEL_DROPIN.read_text() == GRUB_LABEL_DROPIN_BODY:
                return False
        except OSError:
            pass
    if dry_run:
        log.info(f"would write {GRUB_LABEL_DROPIN}")
        return True
    run_sudo(["mkdir", "-p", str(GRUB_LABEL_DROPIN.parent)])
    run_sudo(["tee", str(GRUB_LABEL_DROPIN)], input_str=GRUB_LABEL_DROPIN_BODY, capture=True)
    log.ok(f"wrote GRUB label drop-in {GRUB_LABEL_DROPIN}")
    return True
